# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://bakasheddy.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /Portfolio

# Title of the Site
title: Shedrack David
# Description of the Site
description: I am a Data Analyst, I strive to provide actionable insights to drive business decisions and i can actually tell interesting stories through data.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /Portfolio/assets/images/favicon.ico
    

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: shedrackdavid9@gmail.com
facebook_username: baka.sheddy.5
twitter_username: BakaSheddy
instagram_username: 
linkedin_username: shedrack-david-1a116b235
github_username:  bakasheddy
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Baka Sheddy

# Name of the Author
author-name: Shedrack David
# URL for the Image of the Author
author-image: /Portfolio/assets/images/profil.jpg

# 60 Words About the Author
author-about: Greetings! My name is Shedrack David, and I am a data analyst. Some people say that analyzing data is boring, but for me, it is like trying to solve a mystery, and I love a good puzzle! I spend most of my days poring over spreadsheets, charts, and graphs, looking for insights and patterns that others might miss. But when I am not working, you can find me indulging in some of my other passions. For instance, I love listening to music. I believe that music can soothe the soul and inspire creativity, and it is also a great way to take a break from the grind. Another way I like to unwind is by watching documentaries and podcasts about philosophy, cosmology, and data science. I find these topics fascinating because they help me understand the universe and our place in it. Plus, it is always fun to nerd out with like-minded people! When I am not exploring the mysteries of the universe, you might find me playing video games or watching anime. I know, I know - some people might say that video games and anime are just for kids. But I believe that there is something special about being able to lose yourself in a fictional world, whether you are saving a princess or battling giant robots. So if you ever need to like talk about any of these topics or about life in general, feel free to reachoutðŸ˜Š

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/bakasheddy

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-github-pages


# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
